language: node_js
node_js:
  - '8'
branches:
  only:
    - master
cache:
  npm: true
script:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
  - cd redoc && npm install && npm run build && cd ..
  - cp redoc/api.html docusaurus/pages/api.html
  - cd docusaurus && npm install && GIT_USER="${GH_NAME}" npm run publish-gh-pages && cd ..
